config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "users/new"
  get "/help", to: "pages#help", as: "helf"
  get "/about", to: "pages#about"
  get "/contact", to: "pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t(".announce_footer_html", tutorial: link_to(t(".tutorial_link_detail"),
      t(".tutorial_link")), book: link_to(t(".book_link_detail"), t(".book_link"))) %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t(".footer_about"), about_path %></li>
      <li><%= link_to t(".footer_Contact"), contact_path %></li>
      <li><%= link_to(t(".footer_link_detail"), t(".footer_link")) %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(".heard_info_heard"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".heard_info_home"), root_path %></li>
        <li><%= link_to t(".heard_info_help"), helf_path %></li>
        <% if logged_in? %>
          <li><%= link_to t(".heard_info_user"), users_path %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t(".heard_info_Account") %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".heard_info_Profile"), current_user %></li>
              <li><%= link_to t(".heard_info_Settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".heard_info_logout"), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".heard_info_login"), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>